---
title: "R Notebook"
output: html_notebook
---

############ Demo ###########
```{r}
library(lubridate)
library(dplyr)
library(ggplot2)
library(reshape2)
library(plotly)
```


```{r}
setwd("~/GitHub/Fall2017-project2-grp8/data/flight_data")
demo_data <- read.csv('2017_07_01.csv',header = T)
```

```{r}
demo_data$X <- NULL

demo_data[is.na(demo_data)] <- 0
demo_data$ARR_DELAY[demo_data$ARR_DELAY<0] <- 0
length(unique(demo_data$UNIQUE_CARRIER))
demo_data$month = month(demo_data$FL_DATE, label = T)

demo_data$dest = paste0(demo_data$DEST, " (", demo_data$DEST_CITY_NAME,")")
demo_data$orig = paste0(demo_data$ORIGIN, " (", demo_data$ORIGIN_CITY_NAME,")")
demo_data$carrier = demo_data$UNIQUE_CARRIER
colnames(demo_data)
demo_data[,c('UNIQUE_CARRIER','ORIGIN','ORIGIN_CITY_NAME','DEST','DEST_CITY_NAME')] <- NULL

grp <- demo_data %>% 
  group_by(month, carrier, dest, orig) %>%
  summarise(num_flights = length(month),
            num_delays = sum(ARR_DELAY > 0),
            percent_delays = num_delays/num_flights,
            total_delays = sum(ARR_DELAY),
            percent_carrier_delay = sum(CARRIER_DELAY)/total_delays*percent_delays,
            percent_weather_delay = sum(WEATHER_DELAY)/total_delays*percent_delays,
            percent_NAS_delay = sum(NAS_DELAY)/total_delays*percent_delays,
            percent_late_aircraft_delay = sum(LATE_AIRCRAFT_DELAY)/total_delays*percent_delays,
            percent_security_delay = (1-percent_carrier_delay-percent_weather_delay-
              percent_NAS_delay-percent_late_aircraft_delay)*percent_delays
            ) %>% 
  as.data.frame()


# barplot <- function(m,d,o){
#   data <- grp %>% filter(month==m,dest==d,orig==o)
#   ggplot(data,aes(x=carrier,y=percent_delays))+
#     geom_bar(stat = 'identity')
#   
# }
# barplot('Jul','LAX (Los Angeles, CA)','BOS (Boston, MA)')

stack_barplot <- function(m,d,o){
  mm <- grp %>% 
    filter(month==m,dest==d,orig==o) %>% 
    select(carrier,percent_carrier_delay,percent_weather_delay,percent_NAS_delay,percent_security_delay,percent_late_aircraft_delay) %>% 
    #rename(c('carrier','Carrier','Weather','NAS','Security','Late_aircraft')) %>% 
    melt(id='carrier')
    #rename(variable = delay_reason)
  
  colnames(mm) <- c('carrier','delay_reason','value')
  
  ggplot(mm, aes(x = carrier, y = value, fill = delay_reason)) + 
  geom_bar(stat = "identity")+
  ylab('delay probability')
  
}

stack_barplot('Jul','LAX (Los Angeles, CA)','BOS (Boston, MA)')


```



##  Data preparation ##########
```{r}


prepare_data <- function(data_path, output_file_name){
  files_set = list.files(path = data_path)
  combined_data = data.frame()

	for(file in 1:length(files_set)) {
		# read in each month of data
		tmp = read.csv(paste0(data_path,"/",files_set[file]))
		# rbind monthly data into one data frame
	  combined_data = rbind(combined_data,tmp)
		
		}
		
	combined_data$X <- NULL
  combined_data[is.na(combined_data)] <- 0
  combined_data$ARR_DELAY[combined_data$ARR_DELAY<0] <- 0
  combined_data$month = month(combined_data$FL_DATE, label = T)
  combined_data$dest = paste0(combined_data$DEST, " (", combined_data$DEST_CITY_NAME,")")
  combined_data$orig = paste0(combined_data$ORIGIN, " (", combined_data$ORIGIN_CITY_NAME,")")
  combined_data$carrier = combined_data$UNIQUE_CARRIER
  combined_data[,'UNIQUE_CARRIER'] <- NULL
#,'ORIGIN','ORIGIN_CITY_NAME','DEST','DEST_CITY_NAME'
	write.csv(combined_data,paste0(output_file_name,".csv"),row.names = F)
  return(combined_data)
}


combined <- prepare_data("~/GitHub/Fall2017-project2-grp8/output/flight_0816_0717","0816_0717")

```


## stacked barplot function #########
```{r}
combined <- read.csv("0816_0717.csv")



stack_barplot <- function(m,d,o){
  grp <- combined %>% 
  group_by(month, carrier, dest, orig) %>%
  summarise(num_flights = length(month),
            num_delays = sum(ARR_DELAY > 0),
            percent_delays = num_delays/num_flights,
            total_delays = sum(ARR_DELAY),
            percent_carrier_delay = sum(CARRIER_DELAY)/total_delays*percent_delays,
            percent_weather_delay = sum(WEATHER_DELAY)/total_delays*percent_delays,
            percent_NAS_delay = sum(NAS_DELAY)/total_delays*percent_delays,
            percent_late_aircraft_delay = sum(LATE_AIRCRAFT_DELAY)/total_delays*percent_delays,
            percent_security_delay = (1-percent_carrier_delay-percent_weather_delay-
              percent_NAS_delay-percent_late_aircraft_delay)*percent_delays
            ) %>% 
  as.data.frame()
  
  mm <- grp %>% 
    filter(month==m,dest==d,orig==o) %>% 
    select(carrier,percent_carrier_delay,percent_weather_delay,percent_NAS_delay,percent_security_delay,percent_late_aircraft_delay) %>% 
    #rename(c('carrier','Carrier','Weather','NAS','Security','Late_aircraft')) %>% 
    melt(id='carrier')
    #rename(variable = delay_reason)
  
  colnames(mm) <- c('carrier','delay_reason','value')
  
  ggplot(mm, aes(x = carrier, y = value, fill = delay_reason)) + 
  geom_bar(stat = "identity")+
  ylab('delay probability')
  
}

stack_barplot('Jul','JFK (New York, NY)','BOS (Boston, MA)')


```


## ########### Drafts #############


```{r}
setwd("~/Desktop")
airport_location <- read.csv('airportlocations.csv',header=T)

```

```{r}
setwd("~/GitHub/Fall2017-project2-grp8/output")
grp <- read.csv('grp.csv',header = T)
```

```{r}
library(dplyr)
airport_location <- airport_location %>% filter(IATA %in% unique(airport_abb))

grp$orig <- as.character(grp$orig)
airport_abb <- sapply(grp$orig,function(x){return(strsplit(x,split = ' \\(')[[1]][1])})
length(unique(airport_location$IATA))
length(unique(grp$dest))
length(unique(grp$orig))


# add longitude and latitude to grp
temp <- left_join(grp,airport_location,by=c('ORIGIN'='IATA')) %>% 
  rename(Latitude_orig = Latitude, Longitude_orig = Longitude) %>% 
  left_join(airport_location,by=c('DEST'='IATA')) %>% 
  rename(Latitude_dest = Latitude, Longitude_dest = Longitude)

temp <- temp %>% na.omit()
write.csv(temp,'temp.csv')

temp_2 <- na.omit(temp)

```


## flight line map
```{r}
library(leaflet)
m <- leaflet(data=airport_location[,]) %>% 
  #addMarkers(~Longitude, ~Latitude, popup = ~as.character(IATA), label = ~as.character(IATA)) %>% 
  addTiles() %>% 
  setView(lng = -95.7129, lat = 37.0902, zoom = 4) %>%  
  addProviderTiles(providers$Stamen.Toner)
  
m

grp$path <- paste(grp$ORIGIN,' ', grp$DEST)
grp %>% group_by(path) %>% 
  summarise(orig)

library(geosphere)

gcIntermediate(c(-73.7789,40.6398), c(-118.408,33.9425),
               n=100, 
               addStartEnd=TRUE,
               sp=TRUE) %>% 
  leaflet() %>% 
  setView(lng = -95.7129, lat = 37.0902, zoom = 4) %>%
  addTiles() %>% 
  addProviderTiles(providers$Stamen.Toner) %>% 
  addPolylines(weight=2,color='darkgreen')

gcIntermediate(temp_2[temp_2$ORIGIN=='JFK',c("Longitude_orig","Latitude_orig")],
               temp_2[temp_2$ORIGIN=='JFK',c("Longitude_dest","Latitude_dest")],
               n=100, 
               addStartEnd=TRUE,
               sp=TRUE) %>% 
  leaflet() %>% 
  setView(lng = -95.7129, lat = 37.0902, zoom = 4) %>%
  addTiles() %>% 
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addPolylines(weight=2,color='orange')

which(is.na(temp[,18]))

length(unique(temp$dest))
length(unique(temp$DEST_CITY_NAME))
```


```{r}
library(dplyr)
temp <- read.csv('../../output/temp.csv',header = T)

carrier_grp <- temp %>% 
  group_by(carrier) %>% 
  summarise(num_flights=sum(num_flights),
            percent_delays=mean(percent_delays),
            num_dest = length(unique(orig)),
            delay_time_ave = mean(delay_time_ave)
            )


library(plotly)

plot_ly(carrier_grp, x = ~num_flights, y = ~num_dest, text = ~carrier, type = 'scatter', mode = 'markers', size = ~percent_delays, color = ~percent_delays, colors = 'Reds',
        sizes = c(10, 50),
        marker = list(opacity = 0.5, sizemode = 'diameter'))
plot_ly(carrier_grp, x = ~num_flights, y = ~num_dest, text = ~carrier, type = 'scatter', mode = 'markers', size = ~delay_time_ave, color = ~delay_time_ave, colors = 'Reds',
        sizes = c(10, 50),
        marker = list(opacity = 0.5, sizemode = 'diameter'))

```

