---
title: "Data Cleaning"
output: html_notebook
---
This is data cleaning part of Map&Timeline visualization.

## Airport location
```{r}
airportLocation <- read.table(file = "../../../data/FlightViz/airport_location.csv",
                              as.is = T, header = T,sep = ",")
airportLocation <- airportLocation[!duplicated(airportLocation$IATA),]
rownames(airportLocation) <- airportLocation$IATA
airportLocation <- airportLocation[,-1]
colnames(airportLocation) <- c("LON", "LAT")
airportLocation <- na.omit(airportLocation)
```

## Reading Flight Data & Calculate Mean Delay Time
```{r}
i = 2010
for(j in c(1:12)){
    if(j < 10){ j = paste("0", j, sep = "")}
    filenameIn <- paste("../../../data/FlightViz/", i, "/", i, j,".csv", sep = "")
    flightData <- read.table(file = filenameIn, as.is = T, header = T,sep = ",")
    flightData <- flightData[, c(1, 2, 3, 4)]
    flightData <- flightData%>%
      group_by(FL_DATE, ORIGIN, DEST) %>%
      summarise(meanDelay=(mean(DEP_DELAY_NEW)))
    flightData <- na.omit(flightData)
    
    filenameOut <- paste("../../../data/FlightViz/", i, "out/", i, j,"out.csv", sep = "")
    write.table(flightData, file = filenameOut,
                col.names = T, sep = ",")
    print(paste(filenameOut, "done"))
}
```


## Add Airport Location in Each Data Row - final output
```{r}
i = 2010
for(j in c(1:12)){
    if(j < 10){ j = paste("0", j, sep = "")}
    filenameIn <- paste("../../../data/FlightViz/", i, "out/", i, j,"out.csv", sep = "")
    flightData <- read.table(file = filenameIn,
                             as.is = T, header = T,sep = ",")
    #flightData$FL_DATE <- parse_date_time(flightData$FL_DATE, "%Y-%m-%d")
    
    allPairs <- flightData
    allPairs$ORIGIN_Lon <- airportLocation[allPairs[,2],1]
    allPairs$ORIGIN_Lat <- airportLocation[allPairs[,2],2]
    allPairs$DEST_Lon <- airportLocation[allPairs[,3],1]
    allPairs$DEST_Lat <- airportLocation[allPairs[,3],2]
    allPairs <- na.omit(allPairs)
    
    filenameOut <- paste("../../../data/FlightViz/", i, "Fout/", i, j,"Fout.csv", sep = "")
    write.table(allPairs, file = filenameOut,
                col.names = T, sep = ",")
    print(paste(filenameOut, "done"))
}
    
```


## Combine 1990 & 2010 Together
```{r}
i = 1990
tn <- NULL
for(j in c(1:12)){
  if(j < 10){ j = paste("0", j, sep = "")}
  filenameIn <- paste("../../../data/FlightViz/", i, "Fout/", i, j,"Fout.csv", sep = "")
  tmp <- read.csv(filenameIn)
  tn <- rbind(tn, tmp)
}

write.table(tn,file="../../../data/FlightViz/1990.csv", col.names = T, sep = ",")
```



```{r}
    #lines(tmp, col = allPairs()[,"meanDelay"], lwd = 1)
    #inters <- character(0)
    #for(i in 1:nrow(allPairs)){
    #  if( (!is.na(airportLocation[allPairs[i,1],])) & (!is.na(airportLocation[allPairs[i,2],])) ){
    #    inter <- gcIntermediate(airportLocation[allPairs[i,1],], 
    #                            airportLocation[allPairs[i,2],],
    #                            n=10, addStartEnd=TRUE, sp = TRUE, breakAtDateLine = TRUE)
    #    inters <- c(inters, inter)
    #  }
    #}
    #ll0 <- lapply( inters , function(x) `@`(x , "lines") )
    #ll1 <- lapply( unlist( ll0 ) , function(y) `@`(y,"Lines") )
    #SpatialLines( list( Lines( unlist( ll1 ) , ID = 1) ) )







output$timeline  <- renderUI({
    year <- input$YEAR
    if(is.null(year) || is.na(year)){
      print("warning ohahahahaha")
    }else if(year == "1990"){
      flightData <- flightData1990
    }else{
      flightData <- flightData2010
    }
    print(year)
    sliderInput(inputId ="range",
                label = "Time of data collection:",
                min = min(flightData$FL_DATE),
                max = max(flightData$FL_DATE),
                value = min(flightData$FL_DATE),#The initial value
                step = days(),
                animate = animationOptions(interval = 200))
  })

```